format = """\
[](fg:#7AA8F5)\
$hostname\
[](fg:#7AA8F5 bg:#1C3A5E)\
$directory\
[](fg:#1C3A5E bg:#FCF392)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#FCF392)\
$cmd_duration\
$character\
"""

add_newline = false

[hostname]
format = "[ $ssh_symbol$hostname ]($style)"
ssh_symbol = ' '
style = "fg:#000000 bg:#7AA8F5"

[directory]
format = "[ $path ]($style)"
style = "fg:#7DF9AA bg:#1C3A5E"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#000000 bg:#FCF392"

[git_status]
format = '[$all_status]($style)'
style = "fg:#000000 bg:#FCF392"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#FCF392"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[ $duration](bold yellow)"

[character]
success_symbol = '[ \$](bold green) '
error_symbol = '[ \$](bold red) '
